/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "google/protobuf/struct.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(google_protobuf_Struct, google_protobuf_Struct, AUTO)


PB_BIND(google_protobuf_Struct_FieldsEntry, google_protobuf_Struct_FieldsEntry, AUTO)


PB_BIND(google_protobuf_Value, google_protobuf_Value, AUTO)


PB_BIND(google_protobuf_ListValue, google_protobuf_ListValue, AUTO)





#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

