// THIS FILE IS GENERATED BY GDBUF. DO NOT EDIT UNLESS YOU KNOW WHAT YOU'RE DOING
#include <string>
#include "nested.h"
#include "nested.pb.h"
#include <cstdint> // Required for int64_t
#include <type_traits> // Required for std::decay_t
#include <godot_cpp/variant/string.hpp>
#include <godot_cpp/variant/packed_string_array.hpp>
#include "messages.h" // Include the shared utils

namespace gdbuf {
namespace nested {

void DeeplyNestedMessage::_bind_methods() {
  godot::ClassDB::bind_method(godot::D_METHOD("get_proto_file_name"), &DeeplyNestedMessage::get_proto_file_name);
  godot::ClassDB::bind_method(godot::D_METHOD("to_byte_array"), &DeeplyNestedMessage::to_byte_array);
  godot::ClassDB::bind_method(godot::D_METHOD("from_byte_array", "PackedByteArray"), &DeeplyNestedMessage::from_byte_array);
  godot::ClassDB::bind_method(godot::D_METHOD("get_nesting_level"), &DeeplyNestedMessage::get_nesting_level);
  godot::ClassDB::bind_method(godot::D_METHOD("set_nesting_level", "value"), &DeeplyNestedMessage::set_nesting_level);
  godot::ClassDB::add_property("DeeplyNestedMessage", godot::PropertyInfo(godot::Variant::STRING, "nesting_level"
      ), "set_nesting_level", "get_nesting_level");
}

godot::String DeeplyNestedMessage::get_proto_file_name() {
  return godot::String("nested");
}

godot::String DeeplyNestedMessage::_to_string() const {
    godot::String output = "DeeplyNestedMessage {";

    output += "nesting_level: ";
        output += "\"";
        output += this->nesting_level.c_escape();
        output += "\"";

    output += "}";
    return output;
}

// Serialize
godot::PackedByteArray DeeplyNestedMessage::to_byte_array() const {
    struct _nested_deeply_DeeplyNestedMessage proto_msg = nested_deeply_DeeplyNestedMessage_init_zero;
        // --- Singular Field ---
        {
            std::string s = this->nesting_level.utf8().get_data();
            proto_msg.nesting_level = (char*)malloc(s.size() + 1);
            memcpy(proto_msg.nesting_level, s.data(), s.size() + 1);
        } // End fields

    size_t encoded_size;
    if (!pb_get_encoded_size(&encoded_size, nested_deeply_DeeplyNestedMessage_fields, &proto_msg)) {
         pb_release(nested_deeply_DeeplyNestedMessage_fields, &proto_msg);
         return godot::PackedByteArray();
    }

    godot::PackedByteArray ret;
    ret.resize(encoded_size);
    pb_ostream_t stream = pb_ostream_from_buffer(ret.ptrw(), encoded_size);
    
    if (!pb_encode(&stream, nested_deeply_DeeplyNestedMessage_fields, &proto_msg)) {
         godot::UtilityFunctions::printerr("Nanopb encoding failed: ", stream.errmsg);
    }
    
    pb_release(nested_deeply_DeeplyNestedMessage_fields, &proto_msg);
    return ret;
}

// Deserialize
godot::Error DeeplyNestedMessage::from_byte_array(const godot::PackedByteArray &p_bytes) {
    struct _nested_deeply_DeeplyNestedMessage proto_msg = nested_deeply_DeeplyNestedMessage_init_zero;
    pb_istream_t stream = pb_istream_from_buffer(p_bytes.ptr(), p_bytes.size());

    if (!pb_decode(&stream, nested_deeply_DeeplyNestedMessage_fields, &proto_msg)) {
        godot::UtilityFunctions::printerr("Nanopb decoding failed: ", stream.errmsg);
        return godot::ERR_PARSE_ERROR;
    }

    // Map back to Godot
    // Clear Oneofs first
        if (proto_msg.nesting_level) {
            this->nesting_level = godot::String(proto_msg.nesting_level);
        } else {
            this->nesting_level = "";
        }

    pb_release(nested_deeply_DeeplyNestedMessage_fields, &proto_msg);
    return godot::OK;
}
godot::String DeeplyNestedMessage::get_nesting_level() {
  return nesting_level;
}

void DeeplyNestedMessage::set_nesting_level(godot::String p_nesting_level) {
  this->nesting_level = p_nesting_level;
}
}
}
