/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_NESTED_DEEPLY_TEST_PROTO_NESTED_DEEPLY_NESTED_PB_H_INCLUDED
#define PB_NESTED_DEEPLY_TEST_PROTO_NESTED_DEEPLY_NESTED_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _nested_deeply_DeeplyNestedMessage {
    char *nesting_level;
} nested_deeply_DeeplyNestedMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define nested_deeply_DeeplyNestedMessage_init_default {NULL}
#define nested_deeply_DeeplyNestedMessage_init_zero {NULL}

/* Field tags (for use in manual encoding/decoding) */
#define nested_deeply_DeeplyNestedMessage_nesting_level_tag 1

/* Struct field encoding specification for nanopb */
#define nested_deeply_DeeplyNestedMessage_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   nesting_level,     1)
#define nested_deeply_DeeplyNestedMessage_CALLBACK NULL
#define nested_deeply_DeeplyNestedMessage_DEFAULT NULL

extern const pb_msgdesc_t nested_deeply_DeeplyNestedMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define nested_deeply_DeeplyNestedMessage_fields &nested_deeply_DeeplyNestedMessage_msg

/* Maximum encoded size of messages (where known) */
/* nested_deeply_DeeplyNestedMessage_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
