// THIS FILE IS GENERATED BY GDBUF. DO NOT EDIT
#pragma once

#include <string>
#include "godot_cpp/classes/resource.hpp"
#include "godot_cpp/classes/ref.hpp"
#include "godot_cpp/classes/wrapped.hpp"
#include "nested.pb.h"
#include <pb_encode.h>
#include <pb_decode.h>
#include <cstdint> // Required for int64_t
#include <godot_cpp/variant/string.hpp>
#include <godot_cpp/variant/dictionary.hpp>
#include <godot_cpp/variant/array.hpp>
#include <godot_cpp/variant/variant.hpp>

namespace gdbuf {
namespace nested {
class DeeplyNestedMessage;

class DeeplyNestedMessage : public godot::Resource {
  GDCLASS(DeeplyNestedMessage, godot::Resource)

  public:

  protected:
    static void _bind_methods();

  private:
    godot::String nesting_level{};

  public:
    DeeplyNestedMessage() = default;
    ~DeeplyNestedMessage() override = default;
    godot::String get_proto_file_name();

    godot::PackedByteArray to_byte_array() const;
    godot::Error from_byte_array(const godot::PackedByteArray &p_bytes);
    godot::String _to_string() const;
    godot::String get_nesting_level();
    void set_nesting_level(godot::String p_nesting_level);
};
}
}