// THIS FILE IS GENERATED BY GDBUF. DO NOT EDIT
#pragma once

#include <string>
#include "godot_cpp/classes/resource.hpp"
#include "godot_cpp/classes/ref.hpp"
#include "godot_cpp/classes/wrapped.hpp"
#include "dependency.pb.h"
#include <pb_encode.h>
#include <pb_decode.h>
#include <cstdint> // Required for int64_t
#include <godot_cpp/variant/string.hpp>
#include <godot_cpp/variant/dictionary.hpp>
#include <godot_cpp/variant/array.hpp>
#include <godot_cpp/variant/variant.hpp>

namespace gdbuf {
namespace dependency {
class DependencyMessage;

class DependencyMessage : public godot::Resource {
  GDCLASS(DependencyMessage, godot::Resource)

  public:

  protected:
    static void _bind_methods();

  private:
    godot::String name{};

  public:
    DependencyMessage() = default;
    ~DependencyMessage() override = default;
    godot::String get_proto_file_name();

    godot::PackedByteArray to_byte_array() const;
    godot::Error from_byte_array(const godot::PackedByteArray &p_bytes);
    godot::String _to_string() const;
    godot::String get_name();
    void set_name(godot::String p_name);
};
}
}