/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_DEPENDENCY_TEST_PROTO_DEPENDENCY_PB_H_INCLUDED
#define PB_DEPENDENCY_TEST_PROTO_DEPENDENCY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _dependency_DependencyMessage {
    char *name;
} dependency_DependencyMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define dependency_DependencyMessage_init_default {NULL}
#define dependency_DependencyMessage_init_zero   {NULL}

/* Field tags (for use in manual encoding/decoding) */
#define dependency_DependencyMessage_name_tag    1

/* Struct field encoding specification for nanopb */
#define dependency_DependencyMessage_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   name,              1)
#define dependency_DependencyMessage_CALLBACK NULL
#define dependency_DependencyMessage_DEFAULT NULL

extern const pb_msgdesc_t dependency_DependencyMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define dependency_DependencyMessage_fields &dependency_DependencyMessage_msg

/* Maximum encoded size of messages (where known) */
/* dependency_DependencyMessage_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
