// THIS FILE IS GENERATED BY GDBUF. DO NOT EDIT
#pragma once

#include <string>
#include "godot_cpp/classes/resource.hpp"
#include "godot_cpp/classes/ref.hpp"
#include "godot_cpp/classes/wrapped.hpp"
#include "gdbuf_test.pb.h"
#include <pb_encode.h>
#include <pb_decode.h>
#include <cstdint> // Required for int64_t
#include <godot_cpp/variant/string.hpp>
#include <godot_cpp/variant/dictionary.hpp>
#include <godot_cpp/variant/array.hpp>
#include <godot_cpp/variant/variant.hpp>
#include "test/proto/dependency.h"
#include "test/proto/nested/deeply/nested.h"
namespace gdbuf::dependency {
    class DependencyMessage;
}
namespace gdbuf::nested {
    class DeeplyNestedMessage;
}

namespace gdbuf {
namespace gdbuf_test {
class BasicTestMessage;
class SpecialFieldTypesMessage;
class OneOfMessage;
class GoogleWellKnownTypesMessage;
class MapMessage;
class OuterNestedMessage;
class OuterNestedMessageInnerNestedMessage;
class RepeatedComplexMessage;
class RecursiveMessage;
class ReservedMessage;
class EverythingMessage;

class BasicTestMessage : public godot::Resource {
  GDCLASS(BasicTestMessage, godot::Resource)

  public:

  protected:
    static void _bind_methods();

  private:
    double double_field{};
    float float_field{};
    int32_t int32_field{};
    int64_t int64_field{};
    uint32_t uint32_field{};
    uint64_t uint64_field{};
    int32_t sint32_field{};
    int64_t sint64_field{};
    int32_t fixed32_field{};
    int64_t fixed64_field{};
    int32_t sfixed32_field{};
    int64_t sfixed64_field{};
    bool bool_field{};
    godot::String string_field{};
    godot::PackedByteArray bytes_field{};

  public:
    BasicTestMessage() = default;
    ~BasicTestMessage() override = default;
    godot::String get_proto_file_name();

    godot::PackedByteArray to_byte_array() const;
    godot::Error from_byte_array(const godot::PackedByteArray &p_bytes);
    godot::String _to_string() const;
    double get_double_field();
    void set_double_field(double p_double_field);
    float get_float_field();
    void set_float_field(float p_float_field);
    int32_t get_int32_field();
    void set_int32_field(int32_t p_int32_field);
    int64_t get_int64_field();
    void set_int64_field(int64_t p_int64_field);
    uint32_t get_uint32_field();
    void set_uint32_field(uint32_t p_uint32_field);
    uint64_t get_uint64_field();
    void set_uint64_field(uint64_t p_uint64_field);
    int32_t get_sint32_field();
    void set_sint32_field(int32_t p_sint32_field);
    int64_t get_sint64_field();
    void set_sint64_field(int64_t p_sint64_field);
    int32_t get_fixed32_field();
    void set_fixed32_field(int32_t p_fixed32_field);
    int64_t get_fixed64_field();
    void set_fixed64_field(int64_t p_fixed64_field);
    int32_t get_sfixed32_field();
    void set_sfixed32_field(int32_t p_sfixed32_field);
    int64_t get_sfixed64_field();
    void set_sfixed64_field(int64_t p_sfixed64_field);
    bool get_bool_field();
    void set_bool_field(bool p_bool_field);
    godot::String get_string_field();
    void set_string_field(godot::String p_string_field);
    godot::PackedByteArray get_bytes_field();
    void set_bytes_field(godot::PackedByteArray p_bytes_field);
};

class SpecialFieldTypesMessage : public godot::Resource {
  GDCLASS(SpecialFieldTypesMessage, godot::Resource)

  public:
    enum OptionalStringCase {
        _OPTIONAL_STRING_NOT_SET = 0,
    };

  protected:
    static void _bind_methods();

  private:
    OptionalStringCase _optional_string_case = _OPTIONAL_STRING_NOT_SET;
    godot::String optional_string{};
    godot::Array repeated_int32{};
    godot::Array repeated_packed_double{};

  public:
    SpecialFieldTypesMessage() = default;
    ~SpecialFieldTypesMessage() override = default;
    godot::String get_proto_file_name();

    godot::PackedByteArray to_byte_array() const;
    godot::Error from_byte_array(const godot::PackedByteArray &p_bytes);
    godot::String _to_string() const;
    OptionalStringCase get__optional_string_case() const;
    godot::String get_optional_string();
    void set_optional_string(godot::String p_optional_string);
    godot::Array get_repeated_int32();
    void set_repeated_int32(godot::Array p_repeated_int32);
    godot::Array get_repeated_packed_double();
    void set_repeated_packed_double(godot::Array p_repeated_packed_double);
};

class OneOfMessage : public godot::Resource {
  GDCLASS(OneOfMessage, godot::Resource)

  public:
    enum TestOneofCase {
        TEST_ONEOF_NOT_SET = 0,
        kStringField = 1,
        kInt32Field = 2,
        kMessageField = 3,
    };

  protected:
    static void _bind_methods();

  private:
    TestOneofCase test_oneof_case = TEST_ONEOF_NOT_SET;
    godot::String string_field{};
    int32_t int32_field{};
    godot::Ref<BasicTestMessage> message_field;

  public:
    OneOfMessage() = default;
    ~OneOfMessage() override = default;
    godot::String get_proto_file_name();

    godot::PackedByteArray to_byte_array() const;
    godot::Error from_byte_array(const godot::PackedByteArray &p_bytes);
    godot::String _to_string() const;
    TestOneofCase get_test_oneof_case() const;
    godot::String get_string_field();
    void set_string_field(godot::String p_string_field);
    int32_t get_int32_field();
    void set_int32_field(int32_t p_int32_field);
    godot::Ref<BasicTestMessage> get_message_field();
    void set_message_field(const godot::Ref<BasicTestMessage> p_message_field);
};

class GoogleWellKnownTypesMessage : public godot::Resource {
  GDCLASS(GoogleWellKnownTypesMessage, godot::Resource)

  public:

  protected:
    static void _bind_methods();

  private:
    godot::Dictionary any_field{};
    int64_t timestamp_field{};
    double duration_field{};
    godot::String string_wrapper{};
    int32_t int32_wrapper{};
    godot::Dictionary struct_field{};
    godot::Variant empty_field{};

  public:
    GoogleWellKnownTypesMessage() = default;
    ~GoogleWellKnownTypesMessage() override = default;
    godot::String get_proto_file_name();

    godot::PackedByteArray to_byte_array() const;
    godot::Error from_byte_array(const godot::PackedByteArray &p_bytes);
    godot::String _to_string() const;
    godot::Dictionary get_any_field();
    void set_any_field(godot::Dictionary p_any_field);
    int64_t get_timestamp_field();
    void set_timestamp_field(int64_t p_timestamp_field);
    double get_duration_field();
    void set_duration_field(double p_duration_field);
    godot::String get_string_wrapper();
    void set_string_wrapper(godot::String p_string_wrapper);
    int32_t get_int32_wrapper();
    void set_int32_wrapper(int32_t p_int32_wrapper);
    godot::Dictionary get_struct_field();
    void set_struct_field(godot::Dictionary p_struct_field);
    godot::Variant get_empty_field();
    void set_empty_field(godot::Variant p_empty_field);
};

class MapMessage : public godot::Resource {
  GDCLASS(MapMessage, godot::Resource)

  public:

  protected:
    static void _bind_methods();

  private:
    godot::Dictionary string_int_map{};
    godot::Dictionary int_msg_map{};
    godot::Dictionary string_string_map{};

  public:
    MapMessage() = default;
    ~MapMessage() override = default;
    godot::String get_proto_file_name();

    godot::PackedByteArray to_byte_array() const;
    godot::Error from_byte_array(const godot::PackedByteArray &p_bytes);
    godot::String _to_string() const;
    godot::Dictionary get_string_int_map();
    void set_string_int_map(godot::Dictionary p_string_int_map);
    godot::Dictionary get_int_msg_map();
    void set_int_msg_map(godot::Dictionary p_int_msg_map);
    godot::Dictionary get_string_string_map();
    void set_string_string_map(godot::Dictionary p_string_string_map);
};

class OuterNestedMessage : public godot::Resource {
  GDCLASS(OuterNestedMessage, godot::Resource)

  public:

  protected:
    static void _bind_methods();

  private:
    godot::String outer_string{};
    godot::Ref<OuterNestedMessageInnerNestedMessage> inner_msg;

  public:
    OuterNestedMessage() = default;
    ~OuterNestedMessage() override = default;
    godot::String get_proto_file_name();

    godot::PackedByteArray to_byte_array() const;
    godot::Error from_byte_array(const godot::PackedByteArray &p_bytes);
    godot::String _to_string() const;
    godot::String get_outer_string();
    void set_outer_string(godot::String p_outer_string);
    godot::Ref<OuterNestedMessageInnerNestedMessage> get_inner_msg();
    void set_inner_msg(const godot::Ref<OuterNestedMessageInnerNestedMessage> p_inner_msg);
};

class OuterNestedMessageInnerNestedMessage : public godot::Resource {
  GDCLASS(OuterNestedMessageInnerNestedMessage, godot::Resource)

  public:

  protected:
    static void _bind_methods();

  private:
    godot::String inner_string{};

  public:
    OuterNestedMessageInnerNestedMessage() = default;
    ~OuterNestedMessageInnerNestedMessage() override = default;
    godot::String get_proto_file_name();

    godot::PackedByteArray to_byte_array() const;
    godot::Error from_byte_array(const godot::PackedByteArray &p_bytes);
    godot::String _to_string() const;
    godot::String get_inner_string();
    void set_inner_string(godot::String p_inner_string);
};

class RepeatedComplexMessage : public godot::Resource {
  GDCLASS(RepeatedComplexMessage, godot::Resource)

  public:

  protected:
    static void _bind_methods();

  private:
    godot::Array messages{};
    godot::Array enums{};

  public:
    RepeatedComplexMessage() = default;
    ~RepeatedComplexMessage() override = default;
    godot::String get_proto_file_name();

    godot::PackedByteArray to_byte_array() const;
    godot::Error from_byte_array(const godot::PackedByteArray &p_bytes);
    godot::String _to_string() const;
    godot::Array get_messages();
    void set_messages(godot::Array p_messages);
    godot::Array get_enums();
    void set_enums(godot::Array p_enums);
};

class RecursiveMessage : public godot::Resource {
  GDCLASS(RecursiveMessage, godot::Resource)

  public:

  protected:
    static void _bind_methods();

  private:
    godot::String name{};
    godot::Array children{};
    godot::Ref<RecursiveMessage> parent;

  public:
    RecursiveMessage() = default;
    ~RecursiveMessage() override = default;
    godot::String get_proto_file_name();

    godot::PackedByteArray to_byte_array() const;
    godot::Error from_byte_array(const godot::PackedByteArray &p_bytes);
    godot::String _to_string() const;
    godot::String get_name();
    void set_name(godot::String p_name);
    godot::Array get_children();
    void set_children(godot::Array p_children);
    godot::Ref<RecursiveMessage> get_parent();
    void set_parent(const godot::Ref<RecursiveMessage> p_parent);
};

class ReservedMessage : public godot::Resource {
  GDCLASS(ReservedMessage, godot::Resource)

  public:

  protected:
    static void _bind_methods();

  private:

  public:
    ReservedMessage() = default;
    ~ReservedMessage() override = default;
    godot::String get_proto_file_name();

    godot::PackedByteArray to_byte_array() const;
    godot::Error from_byte_array(const godot::PackedByteArray &p_bytes);
    godot::String _to_string() const;
};

class EverythingMessage : public godot::Resource {
  GDCLASS(EverythingMessage, godot::Resource)

  public:

  protected:
    static void _bind_methods();

  private:
    godot::Ref<BasicTestMessage> basic_message;
    godot::Ref<SpecialFieldTypesMessage> special_message;
    godot::Ref<MapMessage> map_message;
    godot::Ref<OneOfMessage> oneof_message;
    godot::Ref<OuterNestedMessage> nested_message;
    godot::Ref<GoogleWellKnownTypesMessage> well_known_types_message;
    int32_t basic_enum{};
    godot::Ref<gdbuf::dependency::DependencyMessage> dependency_message;
    godot::Ref<RepeatedComplexMessage> repeated_complex;
    godot::Ref<RecursiveMessage> recursive;
    godot::Ref<gdbuf::nested::DeeplyNestedMessage> deeply_nested;

  public:
    EverythingMessage() = default;
    ~EverythingMessage() override = default;
    godot::String get_proto_file_name();

    godot::PackedByteArray to_byte_array() const;
    godot::Error from_byte_array(const godot::PackedByteArray &p_bytes);
    godot::String _to_string() const;
    godot::Ref<BasicTestMessage> get_basic_message();
    void set_basic_message(const godot::Ref<BasicTestMessage> p_basic_message);
    godot::Ref<SpecialFieldTypesMessage> get_special_message();
    void set_special_message(const godot::Ref<SpecialFieldTypesMessage> p_special_message);
    godot::Ref<MapMessage> get_map_message();
    void set_map_message(const godot::Ref<MapMessage> p_map_message);
    godot::Ref<OneOfMessage> get_oneof_message();
    void set_oneof_message(const godot::Ref<OneOfMessage> p_oneof_message);
    godot::Ref<OuterNestedMessage> get_nested_message();
    void set_nested_message(const godot::Ref<OuterNestedMessage> p_nested_message);
    godot::Ref<GoogleWellKnownTypesMessage> get_well_known_types_message();
    void set_well_known_types_message(const godot::Ref<GoogleWellKnownTypesMessage> p_well_known_types_message);
    int32_t get_basic_enum();
    void set_basic_enum(int32_t p_basic_enum);
    godot::Ref<gdbuf::dependency::DependencyMessage> get_dependency_message();
    void set_dependency_message(const godot::Ref<gdbuf::dependency::DependencyMessage> p_dependency_message);
    godot::Ref<RepeatedComplexMessage> get_repeated_complex();
    void set_repeated_complex(const godot::Ref<RepeatedComplexMessage> p_repeated_complex);
    godot::Ref<RecursiveMessage> get_recursive();
    void set_recursive(const godot::Ref<RecursiveMessage> p_recursive);
    godot::Ref<gdbuf::nested::DeeplyNestedMessage> get_deeply_nested();
    void set_deeply_nested(const godot::Ref<gdbuf::nested::DeeplyNestedMessage> p_deeply_nested);
};
}
}
VARIANT_ENUM_CAST(gdbuf::gdbuf_test::SpecialFieldTypesMessage::OptionalStringCase);
VARIANT_ENUM_CAST(gdbuf::gdbuf_test::OneOfMessage::TestOneofCase);