/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_TEST_PROTO_GDBUF_TEST_PB_H_INCLUDED
#define PB_TEST_PROTO_GDBUF_TEST_PB_H_INCLUDED
#include <pb.h>
#include "google/protobuf/any.pb.h"
#include "google/protobuf/duration.pb.h"
#include "google/protobuf/empty.pb.h"
#include "google/protobuf/struct.pb.h"
#include "google/protobuf/timestamp.pb.h"
#include "google/protobuf/wrappers.pb.h"
#include "test/proto/dependency.pb.h"
#include "test/proto/nested/deeply/nested.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _BasicTestEnum {
    BasicTestEnum_BASIC_TEST_ENUM_UNSPECIFIED = 0,
    BasicTestEnum_BASIC_TEST_ENUM_ONE = 1,
    BasicTestEnum_BASIC_TEST_ENUM_TWO = 2,
    BasicTestEnum_BASIC_TEST_ENUM_THREE = 3
} BasicTestEnum;

/* Struct definitions */
typedef struct _BasicTestMessage {
    double *double_field;
    float *float_field;
    int32_t *int32_field;
    int64_t *int64_field;
    uint32_t *uint32_field;
    uint64_t *uint64_field;
    int32_t *sint32_field;
    int64_t *sint64_field;
    uint32_t *fixed32_field;
    uint64_t *fixed64_field;
    int32_t *sfixed32_field;
    int64_t *sfixed64_field;
    bool *bool_field;
    char *string_field;
    pb_bytes_array_t *bytes_field;
} BasicTestMessage;

typedef struct _SpecialFieldTypesMessage {
    char *optional_string;
    pb_size_t repeated_int32_count;
    int32_t *repeated_int32;
    pb_size_t repeated_packed_double_count;
    double *repeated_packed_double;
} SpecialFieldTypesMessage;

typedef struct _OneOfMessage {
    pb_size_t which_test_oneof;
    union _OneOfMessage_test_oneof {
        char *string_field;
        int32_t *int32_field;
        struct _BasicTestMessage *message_field;
    } test_oneof;
} OneOfMessage;

typedef struct _GoogleWellKnownTypesMessage {
    struct _google_protobuf_Any *any_field;
    struct _google_protobuf_Timestamp *timestamp_field;
    struct _google_protobuf_Duration *duration_field;
    struct _google_protobuf_StringValue *string_wrapper;
    struct _google_protobuf_Int32Value *int32_wrapper;
    struct _google_protobuf_Struct *struct_field;
    struct _google_protobuf_Empty *empty_field;
} GoogleWellKnownTypesMessage;

typedef struct _MapMessage {
    pb_size_t string_int_map_count;
    struct _MapMessage_StringIntMapEntry *string_int_map;
    pb_size_t int_msg_map_count;
    struct _MapMessage_IntMsgMapEntry *int_msg_map;
    pb_size_t string_string_map_count;
    struct _MapMessage_StringStringMapEntry *string_string_map;
} MapMessage;

typedef struct _MapMessage_StringIntMapEntry {
    char *key;
    int32_t *value;
} MapMessage_StringIntMapEntry;

typedef struct _MapMessage_IntMsgMapEntry {
    int32_t *key;
    struct _BasicTestMessage *value;
} MapMessage_IntMsgMapEntry;

typedef struct _MapMessage_StringStringMapEntry {
    char *key;
    char *value;
} MapMessage_StringStringMapEntry;

typedef struct _OuterNestedMessage {
    char *outer_string;
    struct _OuterNestedMessage_InnerNestedMessage *inner_msg;
} OuterNestedMessage;

typedef struct _OuterNestedMessage_InnerNestedMessage {
    char *inner_string;
} OuterNestedMessage_InnerNestedMessage;

typedef struct _RepeatedComplexMessage {
    pb_size_t messages_count;
    struct _BasicTestMessage *messages;
    pb_size_t enums_count;
    BasicTestEnum *enums;
} RepeatedComplexMessage;

typedef struct _RecursiveMessage {
    char *name;
    pb_size_t children_count;
    struct _RecursiveMessage *children;
    struct _RecursiveMessage *parent;
} RecursiveMessage;

typedef struct _ReservedMessage {
    char dummy_field;
} ReservedMessage;

typedef struct _EverythingMessage {
    struct _BasicTestMessage *basic_message;
    struct _SpecialFieldTypesMessage *special_message;
    struct _MapMessage *map_message;
    struct _OneOfMessage *oneof_message;
    struct _OuterNestedMessage *nested_message;
    struct _GoogleWellKnownTypesMessage *well_known_types_message;
    BasicTestEnum *basic_enum;
    struct _dependency_DependencyMessage *dependency_message;
    struct _RepeatedComplexMessage *repeated_complex;
    struct _RecursiveMessage *recursive;
    struct _nested_deeply_DeeplyNestedMessage *deeply_nested;
} EverythingMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _BasicTestEnum_MIN BasicTestEnum_BASIC_TEST_ENUM_UNSPECIFIED
#define _BasicTestEnum_MAX BasicTestEnum_BASIC_TEST_ENUM_THREE
#define _BasicTestEnum_ARRAYSIZE ((BasicTestEnum)(BasicTestEnum_BASIC_TEST_ENUM_THREE+1))











#define RepeatedComplexMessage_enums_ENUMTYPE BasicTestEnum



#define EverythingMessage_basic_enum_ENUMTYPE BasicTestEnum


/* Initializer values for message structs */
#define BasicTestMessage_init_default            {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL}
#define SpecialFieldTypesMessage_init_default    {NULL, 0, NULL, 0, NULL}
#define OneOfMessage_init_default                {0, {NULL}}
#define GoogleWellKnownTypesMessage_init_default {NULL, NULL, NULL, NULL, NULL, NULL, NULL}
#define MapMessage_init_default                  {0, NULL, 0, NULL, 0, NULL}
#define MapMessage_StringIntMapEntry_init_default {NULL, NULL}
#define MapMessage_IntMsgMapEntry_init_default   {NULL, NULL}
#define MapMessage_StringStringMapEntry_init_default {NULL, NULL}
#define OuterNestedMessage_init_default          {NULL, NULL}
#define OuterNestedMessage_InnerNestedMessage_init_default {NULL}
#define RepeatedComplexMessage_init_default      {0, NULL, 0, NULL}
#define RecursiveMessage_init_default            {NULL, 0, NULL, NULL}
#define ReservedMessage_init_default             {0}
#define EverythingMessage_init_default           {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL}
#define BasicTestMessage_init_zero               {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL}
#define SpecialFieldTypesMessage_init_zero       {NULL, 0, NULL, 0, NULL}
#define OneOfMessage_init_zero                   {0, {NULL}}
#define GoogleWellKnownTypesMessage_init_zero    {NULL, NULL, NULL, NULL, NULL, NULL, NULL}
#define MapMessage_init_zero                     {0, NULL, 0, NULL, 0, NULL}
#define MapMessage_StringIntMapEntry_init_zero   {NULL, NULL}
#define MapMessage_IntMsgMapEntry_init_zero      {NULL, NULL}
#define MapMessage_StringStringMapEntry_init_zero {NULL, NULL}
#define OuterNestedMessage_init_zero             {NULL, NULL}
#define OuterNestedMessage_InnerNestedMessage_init_zero {NULL}
#define RepeatedComplexMessage_init_zero         {0, NULL, 0, NULL}
#define RecursiveMessage_init_zero               {NULL, 0, NULL, NULL}
#define ReservedMessage_init_zero                {0}
#define EverythingMessage_init_zero              {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL}

/* Field tags (for use in manual encoding/decoding) */
#define BasicTestMessage_double_field_tag        1
#define BasicTestMessage_float_field_tag         2
#define BasicTestMessage_int32_field_tag         3
#define BasicTestMessage_int64_field_tag         4
#define BasicTestMessage_uint32_field_tag        5
#define BasicTestMessage_uint64_field_tag        6
#define BasicTestMessage_sint32_field_tag        7
#define BasicTestMessage_sint64_field_tag        8
#define BasicTestMessage_fixed32_field_tag       9
#define BasicTestMessage_fixed64_field_tag       10
#define BasicTestMessage_sfixed32_field_tag      11
#define BasicTestMessage_sfixed64_field_tag      12
#define BasicTestMessage_bool_field_tag          13
#define BasicTestMessage_string_field_tag        14
#define BasicTestMessage_bytes_field_tag         15
#define SpecialFieldTypesMessage_optional_string_tag 1
#define SpecialFieldTypesMessage_repeated_int32_tag 2
#define SpecialFieldTypesMessage_repeated_packed_double_tag 3
#define OneOfMessage_string_field_tag            1
#define OneOfMessage_int32_field_tag             2
#define OneOfMessage_message_field_tag           3
#define GoogleWellKnownTypesMessage_any_field_tag 1
#define GoogleWellKnownTypesMessage_timestamp_field_tag 2
#define GoogleWellKnownTypesMessage_duration_field_tag 3
#define GoogleWellKnownTypesMessage_string_wrapper_tag 4
#define GoogleWellKnownTypesMessage_int32_wrapper_tag 5
#define GoogleWellKnownTypesMessage_struct_field_tag 6
#define GoogleWellKnownTypesMessage_empty_field_tag 7
#define MapMessage_string_int_map_tag            1
#define MapMessage_int_msg_map_tag               2
#define MapMessage_string_string_map_tag         3
#define MapMessage_StringIntMapEntry_key_tag     1
#define MapMessage_StringIntMapEntry_value_tag   2
#define MapMessage_IntMsgMapEntry_key_tag        1
#define MapMessage_IntMsgMapEntry_value_tag      2
#define MapMessage_StringStringMapEntry_key_tag  1
#define MapMessage_StringStringMapEntry_value_tag 2
#define OuterNestedMessage_outer_string_tag      1
#define OuterNestedMessage_inner_msg_tag         2
#define OuterNestedMessage_InnerNestedMessage_inner_string_tag 1
#define RepeatedComplexMessage_messages_tag      1
#define RepeatedComplexMessage_enums_tag         2
#define RecursiveMessage_name_tag                1
#define RecursiveMessage_children_tag            2
#define RecursiveMessage_parent_tag              3
#define EverythingMessage_basic_message_tag      1
#define EverythingMessage_special_message_tag    2
#define EverythingMessage_map_message_tag        3
#define EverythingMessage_oneof_message_tag      4
#define EverythingMessage_nested_message_tag     5
#define EverythingMessage_well_known_types_message_tag 6
#define EverythingMessage_basic_enum_tag         7
#define EverythingMessage_dependency_message_tag 8
#define EverythingMessage_repeated_complex_tag   9
#define EverythingMessage_recursive_tag          10
#define EverythingMessage_deeply_nested_tag      11

/* Struct field encoding specification for nanopb */
#define BasicTestMessage_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, DOUBLE,   double_field,      1) \
X(a, POINTER,  SINGULAR, FLOAT,    float_field,       2) \
X(a, POINTER,  SINGULAR, INT32,    int32_field,       3) \
X(a, POINTER,  SINGULAR, INT64,    int64_field,       4) \
X(a, POINTER,  SINGULAR, UINT32,   uint32_field,      5) \
X(a, POINTER,  SINGULAR, UINT64,   uint64_field,      6) \
X(a, POINTER,  SINGULAR, SINT32,   sint32_field,      7) \
X(a, POINTER,  SINGULAR, SINT64,   sint64_field,      8) \
X(a, POINTER,  SINGULAR, FIXED32,  fixed32_field,     9) \
X(a, POINTER,  SINGULAR, FIXED64,  fixed64_field,    10) \
X(a, POINTER,  SINGULAR, SFIXED32, sfixed32_field,   11) \
X(a, POINTER,  SINGULAR, SFIXED64, sfixed64_field,   12) \
X(a, POINTER,  SINGULAR, BOOL,     bool_field,       13) \
X(a, POINTER,  SINGULAR, STRING,   string_field,     14) \
X(a, POINTER,  SINGULAR, BYTES,    bytes_field,      15)
#define BasicTestMessage_CALLBACK NULL
#define BasicTestMessage_DEFAULT NULL

#define SpecialFieldTypesMessage_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, STRING,   optional_string,   1) \
X(a, POINTER,  REPEATED, INT32,    repeated_int32,    2) \
X(a, POINTER,  REPEATED, DOUBLE,   repeated_packed_double,   3)
#define SpecialFieldTypesMessage_CALLBACK NULL
#define SpecialFieldTypesMessage_DEFAULT NULL

#define OneOfMessage_FIELDLIST(X, a) \
X(a, POINTER,  ONEOF,    STRING,   (test_oneof,string_field,test_oneof.string_field),   1) \
X(a, POINTER,  ONEOF,    INT32,    (test_oneof,int32_field,test_oneof.int32_field),   2) \
X(a, POINTER,  ONEOF,    MESSAGE,  (test_oneof,message_field,test_oneof.message_field),   3)
#define OneOfMessage_CALLBACK NULL
#define OneOfMessage_DEFAULT NULL
#define OneOfMessage_test_oneof_message_field_MSGTYPE BasicTestMessage

#define GoogleWellKnownTypesMessage_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  any_field,         1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  timestamp_field,   2) \
X(a, POINTER,  OPTIONAL, MESSAGE,  duration_field,    3) \
X(a, POINTER,  OPTIONAL, MESSAGE,  string_wrapper,    4) \
X(a, POINTER,  OPTIONAL, MESSAGE,  int32_wrapper,     5) \
X(a, POINTER,  OPTIONAL, MESSAGE,  struct_field,      6) \
X(a, POINTER,  OPTIONAL, MESSAGE,  empty_field,       7)
#define GoogleWellKnownTypesMessage_CALLBACK NULL
#define GoogleWellKnownTypesMessage_DEFAULT NULL
#define GoogleWellKnownTypesMessage_any_field_MSGTYPE google_protobuf_Any
#define GoogleWellKnownTypesMessage_timestamp_field_MSGTYPE google_protobuf_Timestamp
#define GoogleWellKnownTypesMessage_duration_field_MSGTYPE google_protobuf_Duration
#define GoogleWellKnownTypesMessage_string_wrapper_MSGTYPE google_protobuf_StringValue
#define GoogleWellKnownTypesMessage_int32_wrapper_MSGTYPE google_protobuf_Int32Value
#define GoogleWellKnownTypesMessage_struct_field_MSGTYPE google_protobuf_Struct
#define GoogleWellKnownTypesMessage_empty_field_MSGTYPE google_protobuf_Empty

#define MapMessage_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  string_int_map,    1) \
X(a, POINTER,  REPEATED, MESSAGE,  int_msg_map,       2) \
X(a, POINTER,  REPEATED, MESSAGE,  string_string_map,   3)
#define MapMessage_CALLBACK NULL
#define MapMessage_DEFAULT NULL
#define MapMessage_string_int_map_MSGTYPE MapMessage_StringIntMapEntry
#define MapMessage_int_msg_map_MSGTYPE MapMessage_IntMsgMapEntry
#define MapMessage_string_string_map_MSGTYPE MapMessage_StringStringMapEntry

#define MapMessage_StringIntMapEntry_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   key,               1) \
X(a, POINTER,  SINGULAR, INT32,    value,             2)
#define MapMessage_StringIntMapEntry_CALLBACK NULL
#define MapMessage_StringIntMapEntry_DEFAULT NULL

#define MapMessage_IntMsgMapEntry_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, INT32,    key,               1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  value,             2)
#define MapMessage_IntMsgMapEntry_CALLBACK NULL
#define MapMessage_IntMsgMapEntry_DEFAULT NULL
#define MapMessage_IntMsgMapEntry_value_MSGTYPE BasicTestMessage

#define MapMessage_StringStringMapEntry_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   key,               1) \
X(a, POINTER,  SINGULAR, STRING,   value,             2)
#define MapMessage_StringStringMapEntry_CALLBACK NULL
#define MapMessage_StringStringMapEntry_DEFAULT NULL

#define OuterNestedMessage_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   outer_string,      1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  inner_msg,         2)
#define OuterNestedMessage_CALLBACK NULL
#define OuterNestedMessage_DEFAULT NULL
#define OuterNestedMessage_inner_msg_MSGTYPE OuterNestedMessage_InnerNestedMessage

#define OuterNestedMessage_InnerNestedMessage_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   inner_string,      1)
#define OuterNestedMessage_InnerNestedMessage_CALLBACK NULL
#define OuterNestedMessage_InnerNestedMessage_DEFAULT NULL

#define RepeatedComplexMessage_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  messages,          1) \
X(a, POINTER,  REPEATED, UENUM,    enums,             2)
#define RepeatedComplexMessage_CALLBACK NULL
#define RepeatedComplexMessage_DEFAULT NULL
#define RepeatedComplexMessage_messages_MSGTYPE BasicTestMessage

#define RecursiveMessage_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   name,              1) \
X(a, POINTER,  REPEATED, MESSAGE,  children,          2) \
X(a, POINTER,  OPTIONAL, MESSAGE,  parent,            3)
#define RecursiveMessage_CALLBACK NULL
#define RecursiveMessage_DEFAULT NULL
#define RecursiveMessage_children_MSGTYPE RecursiveMessage
#define RecursiveMessage_parent_MSGTYPE RecursiveMessage

#define ReservedMessage_FIELDLIST(X, a) \

#define ReservedMessage_CALLBACK NULL
#define ReservedMessage_DEFAULT NULL

#define EverythingMessage_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  basic_message,     1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  special_message,   2) \
X(a, POINTER,  OPTIONAL, MESSAGE,  map_message,       3) \
X(a, POINTER,  OPTIONAL, MESSAGE,  oneof_message,     4) \
X(a, POINTER,  OPTIONAL, MESSAGE,  nested_message,    5) \
X(a, POINTER,  OPTIONAL, MESSAGE,  well_known_types_message,   6) \
X(a, POINTER,  SINGULAR, UENUM,    basic_enum,        7) \
X(a, POINTER,  OPTIONAL, MESSAGE,  dependency_message,   8) \
X(a, POINTER,  OPTIONAL, MESSAGE,  repeated_complex,   9) \
X(a, POINTER,  OPTIONAL, MESSAGE,  recursive,        10) \
X(a, POINTER,  OPTIONAL, MESSAGE,  deeply_nested,    11)
#define EverythingMessage_CALLBACK NULL
#define EverythingMessage_DEFAULT NULL
#define EverythingMessage_basic_message_MSGTYPE BasicTestMessage
#define EverythingMessage_special_message_MSGTYPE SpecialFieldTypesMessage
#define EverythingMessage_map_message_MSGTYPE MapMessage
#define EverythingMessage_oneof_message_MSGTYPE OneOfMessage
#define EverythingMessage_nested_message_MSGTYPE OuterNestedMessage
#define EverythingMessage_well_known_types_message_MSGTYPE GoogleWellKnownTypesMessage
#define EverythingMessage_dependency_message_MSGTYPE dependency_DependencyMessage
#define EverythingMessage_repeated_complex_MSGTYPE RepeatedComplexMessage
#define EverythingMessage_recursive_MSGTYPE RecursiveMessage
#define EverythingMessage_deeply_nested_MSGTYPE nested_deeply_DeeplyNestedMessage

extern const pb_msgdesc_t BasicTestMessage_msg;
extern const pb_msgdesc_t SpecialFieldTypesMessage_msg;
extern const pb_msgdesc_t OneOfMessage_msg;
extern const pb_msgdesc_t GoogleWellKnownTypesMessage_msg;
extern const pb_msgdesc_t MapMessage_msg;
extern const pb_msgdesc_t MapMessage_StringIntMapEntry_msg;
extern const pb_msgdesc_t MapMessage_IntMsgMapEntry_msg;
extern const pb_msgdesc_t MapMessage_StringStringMapEntry_msg;
extern const pb_msgdesc_t OuterNestedMessage_msg;
extern const pb_msgdesc_t OuterNestedMessage_InnerNestedMessage_msg;
extern const pb_msgdesc_t RepeatedComplexMessage_msg;
extern const pb_msgdesc_t RecursiveMessage_msg;
extern const pb_msgdesc_t ReservedMessage_msg;
extern const pb_msgdesc_t EverythingMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define BasicTestMessage_fields &BasicTestMessage_msg
#define SpecialFieldTypesMessage_fields &SpecialFieldTypesMessage_msg
#define OneOfMessage_fields &OneOfMessage_msg
#define GoogleWellKnownTypesMessage_fields &GoogleWellKnownTypesMessage_msg
#define MapMessage_fields &MapMessage_msg
#define MapMessage_StringIntMapEntry_fields &MapMessage_StringIntMapEntry_msg
#define MapMessage_IntMsgMapEntry_fields &MapMessage_IntMsgMapEntry_msg
#define MapMessage_StringStringMapEntry_fields &MapMessage_StringStringMapEntry_msg
#define OuterNestedMessage_fields &OuterNestedMessage_msg
#define OuterNestedMessage_InnerNestedMessage_fields &OuterNestedMessage_InnerNestedMessage_msg
#define RepeatedComplexMessage_fields &RepeatedComplexMessage_msg
#define RecursiveMessage_fields &RecursiveMessage_msg
#define ReservedMessage_fields &ReservedMessage_msg
#define EverythingMessage_fields &EverythingMessage_msg

/* Maximum encoded size of messages (where known) */
/* BasicTestMessage_size depends on runtime parameters */
/* SpecialFieldTypesMessage_size depends on runtime parameters */
/* OneOfMessage_size depends on runtime parameters */
/* MapMessage_size depends on runtime parameters */
/* MapMessage_StringIntMapEntry_size depends on runtime parameters */
/* MapMessage_IntMsgMapEntry_size depends on runtime parameters */
/* MapMessage_StringStringMapEntry_size depends on runtime parameters */
/* OuterNestedMessage_size depends on runtime parameters */
/* OuterNestedMessage_InnerNestedMessage_size depends on runtime parameters */
/* RepeatedComplexMessage_size depends on runtime parameters */
/* RecursiveMessage_size depends on runtime parameters */
/* EverythingMessage_size depends on runtime parameters */
#if defined(google_protobuf_Any_size) && defined(google_protobuf_StringValue_size) && defined(google_protobuf_Struct_size)
#define GoogleWellKnownTypesMessage_size         (81 + google_protobuf_Any_size + google_protobuf_StringValue_size + google_protobuf_Struct_size)
#define TEST_PROTO_GDBUF_TEST_PB_H_MAX_SIZE      GoogleWellKnownTypesMessage_size
#endif
#define ReservedMessage_size                     0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
