/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "test/proto/gdbuf_test.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(BasicTestMessage, BasicTestMessage, AUTO)


PB_BIND(SpecialFieldTypesMessage, SpecialFieldTypesMessage, AUTO)


PB_BIND(OneOfMessage, OneOfMessage, AUTO)


PB_BIND(GoogleWellKnownTypesMessage, GoogleWellKnownTypesMessage, AUTO)


PB_BIND(MapMessage, MapMessage, AUTO)


PB_BIND(MapMessage_StringIntMapEntry, MapMessage_StringIntMapEntry, AUTO)


PB_BIND(MapMessage_IntMsgMapEntry, MapMessage_IntMsgMapEntry, AUTO)


PB_BIND(MapMessage_StringStringMapEntry, MapMessage_StringStringMapEntry, AUTO)


PB_BIND(OuterNestedMessage, OuterNestedMessage, AUTO)


PB_BIND(OuterNestedMessage_InnerNestedMessage, OuterNestedMessage_InnerNestedMessage, AUTO)


PB_BIND(RepeatedComplexMessage, RepeatedComplexMessage, AUTO)


PB_BIND(RecursiveMessage, RecursiveMessage, AUTO)


PB_BIND(ReservedMessage, ReservedMessage, AUTO)


PB_BIND(EverythingMessage, EverythingMessage, AUTO)





#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

