// THIS FILE IS GENERATED BY GDBUF. DO NOT EDIT
#pragma once

#include "godot_cpp/classes/object.hpp"
#include "godot_cpp/core/class_db.hpp"

namespace gdbuf {

class gdbufgenEnums : public godot::Object {
    GDCLASS(gdbufgenEnums, godot::Object)

public:
    enum BasicTestEnum {
        BASIC_TEST_ENUM_UNSPECIFIED,
        BASIC_TEST_ENUM_ONE,
        BASIC_TEST_ENUM_TWO,
        BASIC_TEST_ENUM_THREE,
    };

protected:
    static void _bind_methods();
};

} // namespace gdbuf
VARIANT_ENUM_CAST(gdbuf::gdbufgenEnums::BasicTestEnum);
