// THIS FILE IS GENERATED BY GDBUF. DO NOT EDIT
#include "global_enums.h"
#include "godot_cpp/core/class_db.hpp"

namespace gdbuf {

void gdbufgenEnums::_bind_methods() {
    godot::ClassDB::bind_integer_constant("gdbufgenEnums", "BasicTestEnum", "BASIC_TEST_ENUM_UNSPECIFIED", BASIC_TEST_ENUM_UNSPECIFIED);
    godot::ClassDB::bind_integer_constant("gdbufgenEnums", "BasicTestEnum", "BASIC_TEST_ENUM_ONE", BASIC_TEST_ENUM_ONE);
    godot::ClassDB::bind_integer_constant("gdbufgenEnums", "BasicTestEnum", "BASIC_TEST_ENUM_TWO", BASIC_TEST_ENUM_TWO);
    godot::ClassDB::bind_integer_constant("gdbufgenEnums", "BasicTestEnum", "BASIC_TEST_ENUM_THREE", BASIC_TEST_ENUM_THREE);
}

} // namespace gdbuf
